// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkMenuByID = `-- name: CheckMenuByID :one
SELECT 1
FROM menu
WHERE id = $1 LIMIT 1
`

func (q *Queries) CheckMenuByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkMenuByID, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkRoleByCode = `-- name: CheckRoleByCode :one
SELECT 1
FROM role
WHERE code = $1 LIMIT 1
`

func (q *Queries) CheckRoleByCode(ctx context.Context, code string) (int32, error) {
	row := q.db.QueryRow(ctx, checkRoleByCode, code)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkRoleByID = `-- name: CheckRoleByID :one
SELECT 1
FROM role
WHERE id = $1 LIMIT 1
`

func (q *Queries) CheckRoleByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkRoleByID, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserByID = `-- name: CheckUserByID :one
SELECT 1
FROM app_user
WHERE id = $1 LIMIT 1
`

func (q *Queries) CheckUserByID(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, checkUserByID, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const checkUserByUsername = `-- name: CheckUserByUsername :one
SELECT 1
FROM app_user
WHERE username = $1 LIMIT 1
`

func (q *Queries) CheckUserByUsername(ctx context.Context, username string) (int32, error) {
	row := q.db.QueryRow(ctx, checkUserByUsername, username)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createMenu = `-- name: CreateMenu :one
INSERT INTO menu (code, name, description, sequence, type, path, property,
parent_id, parent_path, status, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, code, name, description, sequence, type, path, property, parent_id, parent_path, status, created, updated
`

type CreateMenuParams struct {
	Code        string
	Name        string
	Description string
	Sequence    int16
	Type        string
	Path        string
	Property    string
	ParentID    int32
	ParentPath  string
	Status      string
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

func (q *Queries) CreateMenu(ctx context.Context, arg CreateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, createMenu,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Sequence,
		arg.Type,
		arg.Path,
		arg.Property,
		arg.ParentID,
		arg.ParentPath,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Type,
		&i.Path,
		&i.Property,
		&i.ParentID,
		&i.ParentPath,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO role (code, name, description, sequence, status, created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, name, description, sequence, status, created, updated
`

type CreateRoleParams struct {
	Code        string
	Name        string
	Description string
	Sequence    int16
	Status      string
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Sequence,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO app_user (username, password, name, email, phone, remark, status,
created, updated)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, username, password, name, email, phone, remark, status, created, updated
`

type CreateUserParams struct {
	Username string
	Password string
	Name     string
	Email    string
	Phone    string
	Remark   string
	Status   string
	Created  pgtype.Timestamp
	Updated  pgtype.Timestamp
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Remark,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Remark,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const deleteMenu = `-- name: DeleteMenu :exec
DELETE FROM menu
WHERE id = $1
`

func (q *Queries) DeleteMenu(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteMenu, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM role
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM app_user
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getMenu = `-- name: GetMenu :one
SELECT id, code, name, description, sequence, type, path, property, parent_id, parent_path, status, created, updated
FROM menu
WHERE id = $1 LIMIT 1
`

// Menu
func (q *Queries) GetMenu(ctx context.Context, id int32) (Menu, error) {
	row := q.db.QueryRow(ctx, getMenu, id)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Type,
		&i.Path,
		&i.Property,
		&i.ParentID,
		&i.ParentPath,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, code, name, description, sequence, status, created, updated
FROM role
WHERE id = $1 LIMIT 1
`

// Role
func (q *Queries) GetRole(ctx context.Context, id int32) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, password, name, email, phone, remark, status, created, updated
FROM app_user
WHERE id = $1 LIMIT 1
`

// User
func (q *Queries) GetUser(ctx context.Context, id int32) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Remark,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const listRole = `-- name: ListRole :many
SELECT id, code, name, description, sequence, status, created, updated
FROM role
WHERE ($1::VARCHAR = '' OR $1::VARCHAR ILIKE '%' || $1 || '%')
AND ($2::VARCHAR = '' OR $2::VARCHAR = $2)
AND id > $3
ORDER BY sequence, created DESC
LIMIT $4
`

type ListRoleParams struct {
	Column1 string
	Column2 string
	ID      int32
	Limit   int32
}

func (q *Queries) ListRole(ctx context.Context, arg ListRoleParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRole,
		arg.Column1,
		arg.Column2,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.Sequence,
			&i.Status,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUser = `-- name: ListUser :many
SELECT id, username, password, name, email, phone, remark, status, created, updated
FROM app_user
WHERE ($1::VARCHAR = '' OR $1::VARCHAR ILIKE '%' || $1 || '%')
AND ($2::VARCHAR = '' OR $2::VARCHAR ILIKE '%' || $2 || '%')
AND ($3::VARCHAR = '' OR $3::VARCHAR = $3)
AND id > $4
ORDER BY created DESC
LIMIT $5
`

type ListUserParams struct {
	Column1 string
	Column2 string
	Column3 string
	ID      int32
	Limit   int32
}

func (q *Queries) ListUser(ctx context.Context, arg ListUserParams) ([]AppUser, error) {
	rows, err := q.db.Query(ctx, listUser,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.ID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AppUser
	for rows.Next() {
		var i AppUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Password,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Remark,
			&i.Status,
			&i.Created,
			&i.Updated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenu = `-- name: UpdateMenu :one
UPDATE menu
SET code = $2, name = $3, description = $4, sequence = $5, type = $6,
path = $7, property = $8, parent_id = $9, parent_path = $10, status = $11,
created = $12, updated = $13
WHERE id = $1
RETURNING id, code, name, description, sequence, type, path, property, parent_id, parent_path, status, created, updated
`

type UpdateMenuParams struct {
	ID          int32
	Code        string
	Name        string
	Description string
	Sequence    int16
	Type        string
	Path        string
	Property    string
	ParentID    int32
	ParentPath  string
	Status      string
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

func (q *Queries) UpdateMenu(ctx context.Context, arg UpdateMenuParams) (Menu, error) {
	row := q.db.QueryRow(ctx, updateMenu,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Sequence,
		arg.Type,
		arg.Path,
		arg.Property,
		arg.ParentID,
		arg.ParentPath,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Menu
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Type,
		&i.Path,
		&i.Property,
		&i.ParentID,
		&i.ParentPath,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateRole = `-- name: UpdateRole :one
UPDATE role
SET code = $2, name = $3, description = $4, sequence = $5, status = $6,
created = $7, updated = $8
WHERE id = $1
RETURNING id, code, name, description, sequence, status, created, updated
`

type UpdateRoleParams struct {
	ID          int32
	Code        string
	Name        string
	Description string
	Sequence    int16
	Status      string
	Created     pgtype.Timestamp
	Updated     pgtype.Timestamp
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.Sequence,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.Sequence,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE app_user
SET username = $2, password = $3, name = $4, email = $5, phone = $6,
remark = $7, status = $8, created = $9, updated = $10
WHERE id = $1
RETURNING id, username, password, name, email, phone, remark, status, created, updated
`

type UpdateUserParams struct {
	ID       int32
	Username string
	Password string
	Name     string
	Email    string
	Phone    string
	Remark   string
	Status   string
	Created  pgtype.Timestamp
	Updated  pgtype.Timestamp
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AppUser, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Remark,
		arg.Status,
		arg.Created,
		arg.Updated,
	)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Remark,
		&i.Status,
		&i.Created,
		&i.Updated,
	)
	return i, err
}
