// Package controller provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.1-0.20240331212514-80f0b978ef16 DO NOT EDIT.
package controller

// Defines values for UserStatus.
const (
	Activated UserStatus = "activated"
	Frozen    UserStatus = "frozen"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	Email    *string     `json:"email,omitempty"`
	Password *string     `json:"password,omitempty"`
	Phone    *string     `json:"phone,omitempty"`
	Remark   *string     `json:"remark,omitempty"`
	Status   *UserStatus `json:"status,omitempty"`
	Username *string     `json:"username,omitempty"`
}

// UserStatus defines model for User.Status.
type UserStatus string

// GetApiV1UsersParams defines parameters for GetApiV1Users.
type GetApiV1UsersParams struct {
	Username *string `form:"username,omitempty" json:"username,omitempty"`
	Password *string `form:"password,omitempty" json:"password,omitempty"`
}

// PostApiV1UsersJSONRequestBody defines body for PostApiV1Users for application/json ContentType.
type PostApiV1UsersJSONRequestBody = User
